apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: ml-oso-oet
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432 #TargetPort: This is the actual port on which your application is running inside the container.

# https://stackoverflow.com/questions/49981601/difference-between-targetport-and-port-in-kubernetes-service-definition
#if container listens on port 9376, then targetPort: 9376
#
#if a service listens on port 80, then port: 80
#
#Then service ports config looks like below
#
#ports:
# - protocol: TCP
#   port: 80
#   targetPort: 9376
#Finally, request received to the service’s port, and forwarded on the targetPort of the pod.
#
#Share
#Improve this answer
#Follow
